In [ ]:
# 1
import numpy as np
Z = np.zeros(10)
Z[6] = 5
print(Z)

[0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]


In [ ]:
# 2
import numpy as np

a=np.random.random((3,3,3))
print(a)

[[[0.51074483 0.73201882 0.20334921]
  [0.92899904 0.89961672 0.6082592 ]
  [0.23444485 0.05721405 0.02280861]]

 [[0.01244756 0.45204296 0.65221521]
  [0.50993792 0.29814324 0.34736644]
  [0.53379057 0.87036504 0.49382962]]

 [[0.92140171 0.50606558 0.35774148]
  [0.5090802  0.79373934 0.64849139]
  [0.36700441 0.90601516 0.40199112]]]


In [ ]:
# 3
Height = [175, 156, 184, 169, 177, 160, 154]
Weight = [68, 70, 74, 53, 56, 78, 35]

for i in range(len(Height)):
  bmi = (Weight[i] / Height[i] **2) * 10000
  if bmi > 23:
    print(f"Height: {Height[i]}, Weight: {Weight[i]}, BMI: {bmi:.1f}, 체중 상태: 비만")
  elif bmi <= 18:
    print(f"Height: {Height[i]}, Weight: {Weight[i]}, BMI: {bmi:.1f}, 체중 상태: 정상")
  else:
    print(f"Height: {Height[i]}, Weight: {Weight[i]}, BMI: {bmi:.1f}, 체중 상태: 저체중")

Height: 175, Weight: 68, BMI: 22.2, 체중 상태: 저체중
Height: 156, Weight: 70, BMI: 28.8, 체중 상태: 비만
Height: 184, Weight: 74, BMI: 21.9, 체중 상태: 저체중
Height: 169, Weight: 53, BMI: 18.6, 체중 상태: 저체중
Height: 177, Weight: 56, BMI: 17.9, 체중 상태: 정상
Height: 160, Weight: 78, BMI: 30.5, 체중 상태: 비만
Height: 154, Weight: 35, BMI: 14.8, 체중 상태: 정상


In [ ]:
# 4
import pandas as pd
Data = {'age' : [23, 56, 25, 11, 34],
        'name' : ['가연', '영준', '재석', '호동', '미영'],
        'height' : [156, 188, 175, 180, 157]}
Sex = ['female', 'male', 'male', 'female', 'male']

df = pd.DataFrame(Data)
df['Sex'] = Sex

print(df)

   age name  height     Sex
0   23   가연     156  female
1   56   영준     188    male
2   25   재석     175    male
3   11   호동     180  female
4   34   미영     157    male


In [ ]:
import pandas as pd
import numpy as np

n=np.random.randint(0,100,8)

price=n*10
cars=pd.DataFrame({'price':price})
print(cars)

   price
0    360
1    850
2    290
3    620
4    390
5    100
6     30
7    640


In [ ]:
# 6
level = np.where(price <= 300, '저급', np.where(price >= 800, '고급', '중급'))

# 데이터프레임 생성
cars = pd.DataFrame({'Price': price, 'Level': level})

# 데이터프레임 출력
print(cars)

   Price Level
0    460    중급
1    700    중급
2    440    중급
3    990    고급
4    410    중급
5    630    중급
6    200    저급
7    320    중급


In [ ]:
# 7
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()



# 기존 데이터
print("기존 데이터")
irisDf = pd.DataFrame(data = iris.data, columns = iris.feature_names)
irisDf['target'] = iris.target
irisDf['target'] = irisDf['target'].map({0: "setosa", 1: "versicolor", 2: "virginica"})
print(irisDf)



# 결측치 확인
print("결측치 확인")
import pandas as pd
df = pd.DataFrame(iris.data)
print(df.isnull())



# 평균
print(f"평균: {irisDf.mean()}")
# 분산
print(f"분산: {irisDf.var()}")



# 표준화
print("표준화")
from sklearn.preprocessing import StandardScaler

x = iris.data
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
print(x_scaled[:5])



# 정규화
from sklearn.preprocessing import MinMaxScaler
x, y = iris.data, iris.target

sc = MinMaxScaler()
xNorm = sc.fit_transform(x)

print("정규화 데이터")
irisNDf = pd.DataFrame(data = xNorm, columns = iris.feature_names)
irisNDf['target'] = iris.target
irisNDf['target'] = irisNDf['target'].map({0: "setosa", 1: "versicolor", 2: "virginica"})
print(irisNDf)

기존 데이터
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0  

<ipython-input-1-82292f2190f8>:26: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(f"평균: {irisDf.mean()}")
<ipython-input-1-82292f2190f8>:28: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(f"분산: {irisDf.var()}")


In [ ]:
# 8
import pandas as pd
dfcsv = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/서울교통공사_지하철혼잡도정보_20211231.csv', encoding ='cp949')

# 전체데이터출력
print('-----전체데이터출력-----')
print(dfcsv)

dfcsv = dfcsv.replace({'호선' : 15}, 5)
dfcsv = dfcsv.replace({'호선' : 13}, 2)
dfcsv = dfcsv.replace({'호선' : 14}, 2)

print("-----전체데이터-호선오류수정-----")
print(dfcsv)



# 결측치 확인
print("------결측치 확인------")
print(dfcsv.isnull().sum())

# 연변, ... 삭제
dfall = dfcsv.drop(['연번', '호선','역번호','구분', '조사일자', '역명'], axis=1)

print("-----통계값-----")
# 수치형 데이터의 통계값 추출(개수, 평균, 표준편차, 최솟값, 제 1사분위값, 중앙값, 중위값, 제 3분위값, 최댓값)
print(dfall.describe())



# ——————— 1호선
print("----- 1호선 -----")
df1 = dfcsv[dfcsv['호선']==1]
print(df1)



# 연번, … 삭제
df1 = df1.drop(['연번','호선','역번호','구분', '조사일자', '역명'], axis=1)

# 수치형 데이터의 통계값 추출(개수, 평균, 표준편차, 최솟값, 제 1사분위값, 중앙값, 중위값, 제 3분위값, 최댓값)
print(df1.describe())

-----전체데이터출력-----
        연번 조사일자  호선   역번호   역명  구분  5시30분  6시00분  6시30분  7시00분  ...  19시00분  \
0        1   평일   1   150  서울역  상선    6.2   14.6   13.4   26.8  ...    20.0   
1        2   평일   1   150  서울역  하선    9.1    8.6    9.3   15.2  ...    37.5   
2        3   평일   1   151   시청  상선    5.4   10.1   13.0   20.8  ...    24.1   
3        4   평일   1   151   시청  하선    7.0    6.8   10.2   14.5  ...    33.8   
4        5   평일   1   152   종각  상선    5.2   10.8    9.3   13.6  ...    28.8   
...    ...  ...  ..   ...  ...  ..    ...    ...    ...    ...  ...     ...   
1699  1700  일요일   8  2825   신흥  하선    7.0    3.0    2.2    2.1  ...     4.0   
1700  1701  일요일   8  2826   수진  상선    2.4    1.5    3.2    2.2  ...     4.6   
1701  1702  일요일   8  2826   수진  하선    9.3    4.1    2.6    2.1  ...     2.6   
1702  1703  일요일   8  2827   모란  상선    1.6    0.9    2.5    1.3  ...     4.7   
1703  1704  일요일   8  2827   모란  하선    0.0    0.0    0.0    0.0  ...     0.0   

      19시30분  20시00분  20시30분  21시

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
